# Generated by Django 2.1 on 2018-09-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180923_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user',
        ),
    ]
